# Generated by Django 3.2 on 2022-04-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp', models.IntegerField()),
                ('task_type', models.CharField(choices=[('group', 'Group'), ('channel', 'Channel')], max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('tid', models.CharField(editable=False, max_length=30, unique=True)),
                ('owner', models.ForeignKey(on_delete=models.SET(task.models.get_sentinel_user), related_name='tg_accounts', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(related_name='performers', to='task.TelegramTask')),
            ],
        ),
    ]
