# Generated by Django 3.2 on 2022-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='tid',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='telegram id'),
        ),
    ]
