# Generated by Django 3.2 on 2022-04-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_telegramaccount_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='performers', to='task.TelegramTask'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='tid',
            field=models.CharField(max_length=30, unique=True, verbose_name='telegram id'),
        ),
    ]
