# Generated by Django 3.2 on 2022-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_telegramtask_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramtask',
            name='url',
        ),
        migrations.AddField(
            model_name='telegramtask',
            name='chat_id',
            field=models.CharField(default='telegram', max_length=33),
        ),
    ]
