# Generated by Django 3.2 on 2022-04-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220420_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramtask',
            name='creator',
        ),
    ]
