# Generated by Django 3.2 on 2022-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_telegramtask_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='tid',
            field=models.BigIntegerField(unique=True, verbose_name='telegram id'),
        ),
    ]
