# Generated by Django 3.2 on 2022-04-29 18:14

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_telegramaccount_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='token',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=20),
        ),
    ]
