# Generated by Django 3.2 on 2022-05-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_discordaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordaccount',
            name='username',
            field=models.CharField(default='user#0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='discordaccount',
            name='did',
            field=models.CharField(max_length=100, unique=True, verbose_name='discord id'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='tid',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='telegram id'),
        ),
    ]
