# Generated by Django 3.2 on 2022-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20220504_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordtask',
            name='guild_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
