# Generated by Django 3.2 on 2022-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='addresss',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved')], default='p', max_length=10),
        ),
    ]
